// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBooking.Infrastructure.Persistence;

#nullable disable

namespace MovieBooking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250628064923_initial_Create_seed")]
    partial class initial_Create_seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Casts.Cast", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Chris Hemsworth"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Tom Hiddleston"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Natalie Portman"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Scarlett Johansson"
                        });
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Cinemas.Cinema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cinema");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Name = "Event Cinema Adelaide SA",
                            StateId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Name = "Hoyts Melbourne Central VIC",
                            StateId = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Name = "Luna Cinemas Perth WA",
                            StateId = new Guid("44444444-dddd-dddd-dddd-dddddddddddd")
                        });
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Directors.Director", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Steven Spielberg"
                        });
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Genres.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Love Story"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.MovieCasts.MovieCast", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CastId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("MovieCasts");
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.MovieGenres.MovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Mind-bending sci-fi thriller",
                            DirectorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RuntimeMinutes = 148,
                            Status = 20,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Shark attack thriller",
                            DirectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ReleaseDate = new DateTime(1975, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RuntimeMinutes = 124,
                            Status = 20,
                            Title = "Jaws"
                        });
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeatNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TheatreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TheatreId");

                    b.ToTable("Seat");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa"),
                            SeatNo = "A1a",
                            TheatreId = new Guid("bbbbbbbb-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-bbbb-bbbb-bbbbbbbbbbbb"),
                            SeatNo = "A2a",
                            TheatreId = new Guid("bbbbbbbb-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-2222-aaaa-aaaa-aaaaaaaaaaaa"),
                            SeatNo = "B1b",
                            TheatreId = new Guid("bbbbbbbb-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-2222-bbbb-bbbb-bbbbbbbbbbbb"),
                            SeatNo = "B2b",
                            TheatreId = new Guid("bbbbbbbb-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-aaaa-aaaa-aaaaaaaaaaaa"),
                            SeatNo = "C1c",
                            TheatreId = new Guid("bbbbbbbb-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-bbbb-bbbb-bbbbbbbbbbbb"),
                            SeatNo = "C2c",
                            TheatreId = new Guid("bbbbbbbb-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.States.State", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-cccccccccccc"),
                            Name = "NSW"
                        },
                        new
                        {
                            Id = new Guid("55555555-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "QLD"
                        },
                        new
                        {
                            Id = new Guid("44444444-dddd-dddd-dddd-dddddddddddd"),
                            Name = "WA"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "VIC"
                        },
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "SA"
                        });
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Theatres.Theatre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Theatre");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            CinemaId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Name = "Event Theatre 1a",
                            SeatCapacity = 100
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            CinemaId = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Name = "Hoyts Theatre 1a",
                            SeatCapacity = 120
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            CinemaId = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Name = "Luna Theatre 1a",
                            SeatCapacity = 80
                        });
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Cinemas.Cinema", b =>
                {
                    b.HasOne("MovieBooking.Domain.Aggregates.States.State", "State")
                        .WithMany("Cinemas")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Movies.Movie", b =>
                {
                    b.HasOne("MovieBooking.Domain.Aggregates.Directors.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Seats.Seat", b =>
                {
                    b.HasOne("MovieBooking.Domain.Aggregates.Theatres.Theatre", "Theatre")
                        .WithMany("Seats")
                        .HasForeignKey("TheatreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Theatre");
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Theatres.Theatre", b =>
                {
                    b.HasOne("MovieBooking.Domain.Aggregates.Cinemas.Cinema", "Cinema")
                        .WithMany("Theatres")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Cinemas.Cinema", b =>
                {
                    b.Navigation("Theatres");
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Directors.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.States.State", b =>
                {
                    b.Navigation("Cinemas");
                });

            modelBuilder.Entity("MovieBooking.Domain.Aggregates.Theatres.Theatre", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
